### ISSUE TITLE
About training cost

### ISSUE THREAD

**Issue by pansanity666** [facebookresearch/SIEVE#1]
Hi,  

Thanks for your great job.
Could you please provide more info about the training cost, like GPU and memory requirement and training duration. 

Best,

**Comment by nazMahmoud** [comment]
Thank you for your interest.

For pre-training on **medium** scale, we use 8 nodes, each with 8 V100s, and that takes around 7 hours. For pre-training on **large** scale, we use 16 nodes, each with 8 V100s, and that takes around 30 hours.  The number of samples seen during training is fixed for each scale and defined by [DataComp](https://github.com/mlfoundations/datacomp) in the [scale_configs.py](https://github.com/facebookresearch/SIEVE/blob/main/scale_configs.py) file 

We provide an example of pretraining using slurm [here](https://github.com/facebookresearch/SIEVE/blob/main/scripts/slurm_train.sh)

**Comment by pansanity666** [comment]
Thank you for your reply.
